// <auto-generated />
using EcommerceBlazorNETCore.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceBlazorNETCore.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EcommerceBlazorNETCore.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cloud Atlas is the third novel by British author David Mitchell. Published in 2004, it won the British Book Awards Literary Fiction award and the Richard & Judy Book of the Year award. It was short-listed for the Booker Prize, Nebula Award for Best Novel, and Arthur C. Clarke Award, among other accolades. Unusually, it received awards from both the general literary community and the speculative fiction community.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/38/Cloud_atlas.jpg",
                            Price = 9.99m,
                            Title = "Cloud Atlas"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Wool initially follows the story of Holston, the Silo's sheriff. All residents of the Silo have been taught that the outside world is toxic and deadly, and anyone who expresses any desire to go outside is sent to clean the external sensors. Those who are sent outdoors this way inevitably clean the sensors as instructed, but they also inevitably die a few minutes later",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/1b/Hugh_C_Howey_Wool_Omnibus.jpg",
                            Price = 5.99m,
                            Title = "Wool"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Foundation is a science fiction novel by American writer Isaac Asimov. It is the first published in his Foundation Trilogy (later expanded into the Foundation series). Foundation is a cycle of five interrelated short stories, first published as a single book by Gnome Press in 1951. Collectively they tell the early story of the Foundation, an institute founded by psychohistorian Hari Seldon to preserve the best of galactic civilization after the collapse of the Galactic Empire.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/25/Foundation_gnome.jpg",
                            Price = 7.99m,
                            Title = "Foundation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
